name: Deployment auf fly.io

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Frontend bauen
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with: # Kopiert Frontend-Artifakt (Build-Ergebnis)
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: JDK einrichten
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with: # Fügt Frontend-Artifakt in Backend ein
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Mit Maven bauen
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: app2.jar
          path: backend/src/main/resources/static/app2.jar

  deploy-fly:
    runs-on: ubuntu-latest
    needs: build-backend
    environment: # Wird im GitHub-Repository angezeigt
      name: production-fly.io
      url: https://nosnippet.fly.dev/
    env: # Angelegtes GitHub-Secret
      FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app2.jar
          path: backend/target
      - uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: latest
      - run: flyctl deploy # Deployt die Anwendung
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}