name: Deployment auf fly.io

on:
  push:
    branches:
      - master  # Passe an, falls du einen anderen Branch verwendest

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Frontend bauen
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - name: JDK einrichten
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Mit Maven bauen
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: app2.jar
          path: backend/target/app2.jar  # Pfad zur fertigen JAR-Datei

  build-docker:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t steffenrothenberg/nosnippet .
      - name: Push Docker Image
        run: docker push steffenrothenberg/nosnippet

  deploy-fly:
    runs-on: ubuntu-latest
    needs: build-docker
    environment:
      name: production-fly.io
      url: https://nosnippet.fly.dev/
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl deploy --image steffenrothenberg/nosnippet_latest:v1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
